blank_issues_enabled: false
contact_links:
  - name: Feature request or general question
    url: https://github.com/jaysanati/enci-community/discussions
    about: For ideas, questions, or general discussion, please start a Discussion instead of an issue.
